/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FbcButton {
        "color": string;
        "fullWidth"?: boolean;
        "loading"?: boolean;
        "rest": HTMLButtonElement;
        "underline"?: boolean;
        "variant": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFbcButtonElement extends Components.FbcButton, HTMLStencilElement {
    }
    var HTMLFbcButtonElement: {
        prototype: HTMLFbcButtonElement;
        new (): HTMLFbcButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "fbc-button": HTMLFbcButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FbcButton {
        "color"?: string;
        "fullWidth"?: boolean;
        "loading"?: boolean;
        "rest"?: HTMLButtonElement;
        "underline"?: boolean;
        "variant"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "fbc-button": FbcButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fbc-button": LocalJSX.FbcButton & JSXBase.HTMLAttributes<HTMLFbcButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
